### ISSUE TITLE
Pin avro-python to 1.9.1

### ISSUE THREAD

**Issue by jonathansick** [lsst-sqre/squarebot#11]
avro-python3 1.9.2 was just released and has broken its own installation ([CI](https://travis-ci.com/lsst-sqre/sqrbot-jr/builds/148597232)):

```
4.06s$ make install
180pip install -e ".[dev]"
181Obtaining file:///home/travis/build/lsst-sqre/sqrbot-jr
182Collecting aiodns==1.1.1 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
183  Downloading https://files.pythonhosted.org/packages/bd/f5/b69cb930fd5ab0569396659afe3f3c0d37d4098e5d0ba6afdf6fd9388cb0/aiodns-1.1.1-py2.py3-none-any.whl
184Collecting aiohttp==3.5.0 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
185  Downloading https://files.pythonhosted.org/packages/38/a8/74ec4b28e1d13acd2a3d4196cc0753d0f50afe9eb571ccda1358c75cdb9a/aiohttp-3.5.0-cp37-cp37m-manylinux1_x86_64.whl (1.1MB)
186Collecting cchardet==2.1.4 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
187  Downloading https://files.pythonhosted.org/packages/de/3e/9744f7aeed36226cd26101b26bdba890c2673f1956396b5c33e059785410/cchardet-2.1.4-cp37-cp37m-manylinux1_x86_64.whl (205kB)
188Collecting structlog==18.2.0 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
189  Downloading https://files.pythonhosted.org/packages/f0/00/0fd0ca13fa19361bec0418e4c3b6b7509048cb1fb2fa8b7cd6b3dffe13d8/structlog-18.2.0-py2.py3-none-any.whl
190Collecting colorama==0.4.1 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
191  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
192Collecting click<7.0,>=6.7 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
193  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
194Collecting fastavro==0.21.16 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
195  Downloading https://files.pythonhosted.org/packages/18/2d/4b91f7c0e46068261d07a1c72f810e28aa961f7c2449908729dca97f2944/fastavro-0.21.16-cp37-cp37m-manylinux1_x86_64.whl (1.2MB)
196Collecting kafkit==0.1.1 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
197  Downloading https://files.pythonhosted.org/packages/90/ed/19e0a4a80cdfdb3adc97bbf042ce867a85633eb26e7069b14f8bb38c8d13/kafkit-0.1.1-py3-none-any.whl
198Collecting aiokafka==0.5.2 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
199  Downloading https://files.pythonhosted.org/packages/f3/0f/1cf852cc1945a919e2dff22aa3c9f4d3be26c216ad0104fb3602e428f099/aiokafka-0.5.2.tar.gz (352kB)
200Collecting confluent-kafka==0.11.6 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
201  Downloading https://files.pythonhosted.org/packages/2a/ba/dccb27376453f91ad8fa57f75a7ba5dc188023700c1789273dec976477b2/confluent_kafka-0.11.6-cp37-cp37m-manylinux1_x86_64.whl (3.9MB)
202Collecting pytest==4.2.0 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
203  Downloading https://files.pythonhosted.org/packages/0d/c4/8093b4ffdde66628d4cb138d1d53726e2c21c23ac397cb75494e3f4310c9/pytest-4.2.0-py2.py3-none-any.whl (218kB)
204Collecting pytest-flake8==1.0.4 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
205  Downloading https://files.pythonhosted.org/packages/4b/99/a6e993c0927665522602058e1f2ea61ba1c8c51a60e3006f1eb1153b37e2/pytest_flake8-1.0.4-py2.py3-none-any.whl
206Collecting aiohttp-devtools==0.11 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
207  Downloading https://files.pythonhosted.org/packages/8f/b1/2fc61f56db16ee2fe81d7561a55d5db9028855a30817f048c92f2072fdbd/aiohttp_devtools-0.11-py35.py36-none-any.whl (46kB)
208Collecting avro-python3>=1.9.1 (from sqrbotjr==0.6.1.dev2+gc6bb41a)
209  Downloading https://files.pythonhosted.org/packages/31/21/d98e2515e5ca0337d7e747e8065227ee77faf5c817bbb74391899613178a/avro-python3-1.9.2.tar.gz
210    Complete output from command python setup.py egg_info:
211    Traceback (most recent call last):
212      File "<string>", line 1, in <module>
213      File "/tmp/pip-install-20f8mefq/avro-python3/setup.py", line 41, in <module>
214        import pycodestyle
215    ModuleNotFoundError: No module named 'pycodestyle'
```

The proper route would be to pin avro-python to 1.9.1 or wait for them to re-release.

**Comment by michalspondr** [comment]
Same problem here with 1.9.2

> 
> Collecting avro-python3
>   Downloading https://files.pythonhosted.org/packages/31/21/d98e2515e5ca0337d7e747e8065227ee77faf5c817bbb74391899613178a/avro-python3-1.9.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-b4q6bh1f/avro-python3/setup.py", line 41, in <module>
>         import pycodestyle
>     ModuleNotFoundError: No module named 'pycodestyle'
